name: luvlab
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49979
title: Building ideas we luv
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff7f80'
    - '#ffffff'
    - '#ff9495'
    - '#ffbcbc'
    - '#ffdfdf'
  brandStrength: 0.625
  lightness: 1
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
